service: aws-python-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  get_upload_url:
    handler: functions/handlers/upload.handler
    environment:
      BUCKET: geraldostestbucket3131
    events:
      - httpApi:
          path: /upload_url
          method: get
  download:
    handler: functions/handlers/download.handler
    environment:
      BUCKET: geraldostestbucket3131
    events:
      - httpApi:
          path: /{file_name}
          method: get

plugins:
  - serverless-offline
